name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  api_client:
    path: ../../packages/api_client
  core_ui:
    path: ../../packages/core_ui
  cupertino_icons: ^1.0.8
  database:
    path: ../../packages/database
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  go_router: ^12.0.0
  riverpod_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true
